---
- name: Generate Reports of Pending Upgrades on Systems
  hosts: all
  become: yes

  vars:
    html_report_path: /tmp/reports/reports/upgrades_report.html
    adoc_report_path: /tmp/reports/reports/upgrades_report.adoc
    git_repo_path: /tmp/reports
    git_commit_message: "Updated upgrade reports"
    git_remote_repo: "https://github.com/R0tt3nT0m4t0/reports.git"
  
  tasks:

    - name: Gather list of packages that need to be upgraded
      ansible.builtin.command:
        cmd: "{{ ansible_pkg_mgr }} list updates"
      register: pkg_list

    - name: Clone the Reports Repo
      ansible.builtin.git:
        repo: "{{ git_remote_repo }}"
        dest: /tmp/reports.tmp
        version: main
        force: yes

#    - name: Ensure git repository is initialized
#      ansible.builtin.command:
#        cmd: git init
#        chdir: "{{ git_repo_path }}"
#      args:
#        creates: "{{ git_repo_path }}/.git"

#    - name: Generate HTML report using Jinja2 template
#      ansible.builtin.template:
#        src: report.html.j2
#        dest: "{{ html_report_path }}"
#      vars:
#        packages: "{{ pkg_list.stdout_lines }}"

#    - name: Generate Asciidoc report using Jinja2 template
#      ansible.builtin.template:
#        src: report.adoc.j2
#        dest: "{{ adoc_report_path }}"
#      vars:
#        packages: "{{ pkg_list.stdout_lines }}"

#    - name: Copy HTML report to git repository
#      ansible.builtin.copy:
#        src: "{{ html_report_path }}"
#        dest: "{{ git_repo_path }}/package_upgrade_report.html"

#    - name: Copy Asciidoc report to git repository
#      ansible.builtin.copy:
#        src: "{{ adoc_report_path }}"
#        dest: "{{ git_repo_path }}/package_upgrade_report.adoc"

#    - name: Commit changes to git
#      ansible.builtin.command:
#        cmd: git add . && git commit -m "{{ git_commit_message }}"
#        chdir: "{{ git_repo_path }}"

#    - name: Push changes to remote repository
#      ansible.builtin.command:
#        cmd: git push origin master
#        chdir: "{{ git_repo_path }}"

