---
- name: Generate Reports of Pending Upgrades on Systems
  hosts: all
  become: yes

  vars:
    git_repo_path: /tmp/reports.tmp
    git_commit_message: "Updated upgrade reports"
    git_remote_repo: "https://{{ github_token }}@github.com/R0tt3nT0m4t0/reports.git"
    html_report_path: "{{ git_repo_path }}/reports/upgrades_report_{{ ansible_date_time.date }}.html"
    adoc_report_path: "{{ git_repo_path }}/reports/upgrades_report_{{ ansible_date_time.date }}.adoc"
  vars_files:
    - secret.yml

  tasks:

    - name: Record Start Time
      set_fact:
        start_time: "{{ ansible_date_time.epoch }}"

    - name: Gather list of packages that need to be upgraded
      ansible.builtin.command:
        cmd: "{{ ansible_pkg_mgr }} list updates"
      register: pkg_list

    - name: Sleep 10 Seconds to Make it Interesting
      ansible.builtin.command: sleep 10

    - name: Record End Time
      set_fact:
        end_time: "{{ ansible_date_time.epoch }}"

    - name: Calculate Duration
      set_fact:
        duration: "{{ end_time | int - start_time | int }}"

    - name: Clone the Reports Repo
      ansible.builtin.git:
        repo: "{{ git_remote_repo }}"
        dest: "{{ git_repo_path }}"
        version: main
        force: yes

    - name: Generate HTML report using Jinja2 template
      ansible.builtin.template:
        src: report.html.j2
        dest: "{{ html_report_path }}"
      vars:
        start_time: "{{ start_time | int | strftime('%Y-%m-%d %H:%M:%S') }}"
        end_time: "{{ end_time | int | strftime('%Y-%m-%d %H:%M:%S') }}"
        duration: "{{ duration | int | strftime('%Y-%m-%d %H:%M:%S') }} seconds"
        packages: "{{ pkg_list.stdout_lines }}"

    - name: Generate Asciidoc report using Jinja2 template
      ansible.builtin.template:
        src: report.adoc.j2
        dest: "{{ adoc_report_path }}"
      vars:
        start_time: "{{ start_time }}"
        end_time: "{{ end_time }}"
        duration: "{{ duration }} seconds"
        packages: "{{ pkg_list.stdout_lines }}"

    - name: Add New Files
      ansible.builtin.command:
        cmd: git add .
        chdir: "{{ git_repo_path }}"

    - name: Commit Changes
      ansible.builtin.command:
        cmd: git commit -m "{{ git_commit_message }}"
        chdir: "{{ git_repo_path }}"

    - name: Push Reports
      ansible.builtin.command:
        cmd: git push "{{ git_remote_repo }}" main
        chdir: "{{ git_repo_path }}"


