include::attributes.adoc[]

= Package Upgrade Report

== Durations

[%header,cols="1,1",stripes=even,align=center]
|===
|DESCRIPTION | TIME
|Start Time | 1729195314
|End Time | 1729195326
|Duration | 12
|===

== Packages

The following packages need to be upgraded:

- Last metadata expiration check: 0:50:01 ago on Thu 17 Oct 2024 02:11:55 PM CDT.
- Available Upgrades
- deja-dup.x86_64                46.1-2.fc40                      updates         
- firefox.x86_64                 131.0.3-1.fc40                   updates         
- firefox-langpacks.x86_64       131.0.3-1.fc40                   updates         
- fluidsynth-libs.x86_64         2.3.6-2.fc40                     updates         
- google-chrome-stable.x86_64    130.0.6723.58-1                  google-chrome   
- inkscape.x86_64                1.4-1.fc40                       updates         
- inkscape-libs.x86_64           1.4-1.fc40                       updates         
- javascriptcoregtk4.0.x86_64    2.46.1-2.fc40                    updates         
- kernel.x86_64                  6.11.3-200.fc40                  updates         
- kernel-core.x86_64             6.11.3-200.fc40                  updates         
- kernel-devel.x86_64            6.11.3-200.fc40                  updates         
- kernel-headers.x86_64          6.11.3-200.fc40                  updates         
- kernel-modules.x86_64          6.11.3-200.fc40                  updates         
- kernel-modules-core.x86_64     6.11.3-200.fc40                  updates         
- kernel-modules-extra.x86_64    6.11.3-200.fc40                  updates         
- lib2geom.x86_64                1.4-2.fc40                       updates         
- libgsf.x86_64                  1.14.53-1.fc40                   updates         
- libmysofa.x86_64               1.3.2-3.20240917git2297dd8.fc40  updates         
- libopenmpt.x86_64              0.7.10-1.fc40                    updates         
- nbdkit.x86_64                  1.38.5-1.fc40                    updates         
- nbdkit-basic-filters.x86_64    1.38.5-1.fc40                    updates         
- nbdkit-basic-plugins.x86_64    1.38.5-1.fc40                    updates         
- nbdkit-curl-plugin.x86_64      1.38.5-1.fc40                    updates         
- nbdkit-selinux.noarch          1.38.5-1.fc40                    updates         
- nbdkit-server.x86_64           1.38.5-1.fc40                    updates         
- nbdkit-ssh-plugin.x86_64       1.38.5-1.fc40                    updates         
- python3-virtualenv.noarch      20.21.1-25.fc40                  updates         
- swtpm.x86_64                   0.9.0-2.fc40                     updates         
- swtpm-libs.x86_64              0.9.0-2.fc40                     updates         
- swtpm-selinux.noarch           0.9.0-2.fc40                     updates         
- swtpm-tools.x86_64             0.9.0-2.fc40                     updates         
- systemd.x86_64                 255.13-1.fc40                    updates         
- systemd-container.x86_64       255.13-1.fc40                    updates         
- systemd-devel.x86_64           255.13-1.fc40                    updates         
- systemd-libs.x86_64            255.13-1.fc40                    updates         
- systemd-networkd.x86_64        255.13-1.fc40                    updates         
- systemd-oomd-defaults.noarch   255.13-1.fc40                    updates         
- systemd-pam.x86_64             255.13-1.fc40                    updates         
- systemd-resolved.x86_64        255.13-1.fc40                    updates         
- systemd-udev.x86_64            255.13-1.fc40                    updates         
- tailscale.x86_64               1.76.1-1                         tailscale-stable
- terraform.x86_64               1.9.8-1                          hashicorp       
- toolbox.x86_64                 0.0.99.6-1.fc40                  updates         
- vim-X11.x86_64                 2:9.1.785-1.fc40                 updates         
- vim-common.x86_64              2:9.1.785-1.fc40                 updates         
- vim-data.noarch                2:9.1.785-1.fc40                 updates         
- vim-enhanced.x86_64            2:9.1.785-1.fc40                 updates         
- vim-filesystem.noarch          2:9.1.785-1.fc40                 updates         
- vim-minimal.x86_64             2:9.1.785-1.fc40                 updates         
- wayland-protocols-devel.noarch 1.38-1.fc40                      updates         
- webkit2gtk4.0.x86_64           2.46.1-2.fc40                    updates         
- xxd.x86_64                     2:9.1.785-1.fc40                 updates         

